# docker-compose.yml
version: "3.8"

networks:
  backend:

services:
  basededatos:
    build: ./basededatos
    ports:
      - "5984:5984"
    expose:
      - "5984"
    container_name: basededatos
    healthcheck:
          test: curl --fail http://localhost:5984/ || exit 1
          interval: 10s
          timeout: 5s
          retries: 3
          start_period: 10s
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: admin
    networks:
      - backend

  servidor:
    build: ./servidor
    ports:
      - "8081:8081"
    expose:
      - "8081"
    container_name: servidor
    depends_on:
      basededatos:
        condition: service_healthy
    networks:
      - backend

  interfaz:
    build: ./interfaz
    ports:
      - "8080:8080"
    container_name: interfaz
    expose:
      - "8080"
    depends_on:
      - servidor
    networks:
      - backend
